# <<<<<<< testbranch
# server:
#   port : 8081

# =======
# >>>>>>> main
# debug: false
# management.endpoints.web.exposure.include: "*"

# logging:
#   level:
#     com.verystrong.car_loan_project: debug
#     org.springframework.web.servlet: debug
#     org.hibernate.type.descriptor.sql.BasicBinder: trace

# spring:
# <<<<<<< testbranch
#   jackson:
#     property-naming-strategy: SNAKE_CASE
#   datasource:
#     url: jdbc:mysql://localhost:3306/car_loan_db
#     username: uno
#     password:
# =======
#   datasource:
#     url: jdbc:mysql://localhost:3306/car_loan_db
#     username: uno
#     password: 1234
# >>>>>>> main
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     defer-datasource-initialization: true
#     hibernate.ddl-auto: create
#     show-sql: true
#     properties:
#       hibernate.format_sql: true
#       hibernate.default_batch_fetch_size: 100
#     open-in-view: false
#   servlet:
#     multipart:
#       max-file-size: 10MB
#       max-request-size: 10MB
#       location: "Users/1/Desktop/java/Springboot/car_loan_project/document"
#   sql.init.mode: always
#   data.rest:
#     base-path: /api
#     detection-strategy: annotated
#   thymeleaf3.decoupled-logic: true
# <<<<<<< testbranch

# =======
# >>>>>>> main
