retire_features = ['age', 'familyCount', 'childCount', 'carPrice', 'deposit', 'loanTerm',
       'gender_Man', 'gender_Woman', 'education_College',
       'education_GraduateSchool', 'education_HighSchool',
       'education_MiddleSchool', 'education_University',
       'maritalStatus_Bereaved', 'maritalStatus_Divorced',
       'maritalStatus_Married', 'maritalStatus_Single', 'incomeType_Business',
       'incomeType_Other', 'incomeType_PublicServants',
       'incomeType_Retirement', 'incomeType_Service', 'incomeClass_A',
       'incomeClass_B', 'incomeClass_C', 'incomeClass_D', 'incomeClass_E',
       'incomeClass_F', 'incomeClass_G', 'incomeClass_N',
       'occupation_Cleaning_Laundering', 'occupation_Cooking',
       'occupation_DailyJob', 'occupation_Driving', 'occupation_General_work',
       'occupation_IT_development_management', 'occupation_Labor',
       'occupation_Manager', 'occupation_Other', 'occupation_PersonalService',
       'occupation_Personnel_Manager', 'occupation_Pharmaceutical',
       'occupation_Professional_technology', 'occupation_Sales',
       'occupation_Secretary', 'occupation_Security', 'occupation_Waiter',
       'occupation_accounting', 'occupation_estate_agent',
       'orgType_Agriculture', 'orgType_Army_Police', 'orgType_Bank_insurance',
       'orgType_Cleaning_Laundering', 'orgType_Communications',
       'orgType_Construction', 'orgType_Education',
       'orgType_Foreign_Community', 'orgType_General', 'orgType_Industry',
       'orgType_Kindergarten', 'orgType_Others', 'orgType_Pharmaceutical',
       'orgType_Public', 'orgType_Security', 'orgType_Self_employed',
       'orgType_Service', 'orgType_Trade', 'orgType_Transport',
       'houseOwnedYN_N', 'houseOwnedYN_Y', 'dwellingType_Charter',
       'dwellingType_Family_joint', 'dwellingType_Half_Charter',
       'dwellingType_Monthly_rent', 'dwellingType_N',
       'dwellingType_Public_long_term_rental', 'dwellingType_Self',
       'housingType_Apartment', 'housingType_Detached_house',
       'housingType_Officetel', 'housingType_Related_multifamily_villa',
       'residenceClass_Average', 'residenceClass_Best', 'residenceClass_Good',
       'residenceClass_N', 'carOwnedYN_N', 'carOwnedYN_Y', 'loanType_Autoron',
       'loanType_LoanFinancingType', 'interestType_Fixed',
       'interestType_Mixed', 'interestType_Variable'
           ]
incumbent_features = ['age', 'familyCount', 'childCount', 'employedYears', 'carPrice',
       'deposit', 'loanTerm', 'gender_Man', 'gender_Woman',
       'education_College', 'education_GraduateSchool', 'education_HighSchool',
       'education_MiddleSchool', 'education_University',
       'maritalStatus_Bereaved', 'maritalStatus_Divorced',
       'maritalStatus_Married', 'maritalStatus_Single', 'incomeType_Business',
       'incomeType_Other', 'incomeType_PublicServants',
       'incomeType_Retirement', 'incomeType_Service', 'incomeClass_A',
       'incomeClass_B', 'incomeClass_C', 'incomeClass_D', 'incomeClass_E',
       'incomeClass_F', 'incomeClass_G', 'incomeClass_N',
       'occupation_Cleaning_Laundering', 'occupation_Cooking',
       'occupation_DailyJob', 'occupation_Driving', 'occupation_General_work',
       'occupation_IT_development_management', 'occupation_Labor',
       'occupation_Manager', 'occupation_Other', 'occupation_PersonalService',
       'occupation_Personnel_Manager', 'occupation_Pharmaceutical',
       'occupation_Professional_technology', 'occupation_Sales',
       'occupation_Secretary', 'occupation_Security', 'occupation_Waiter',
       'occupation_accounting', 'occupation_estate_agent',
       'orgType_Agriculture', 'orgType_Army_Police', 'orgType_Bank_insurance',
       'orgType_Cleaning_Laundering', 'orgType_Communications',
       'orgType_Construction', 'orgType_Education',
       'orgType_Foreign_Community', 'orgType_General', 'orgType_Industry',
       'orgType_Kindergarten', 'orgType_Others', 'orgType_Pharmaceutical',
       'orgType_Public', 'orgType_Security', 'orgType_Self_employed',
       'orgType_Service', 'orgType_Trade', 'orgType_Transport',
       'houseOwnedYN_N', 'houseOwnedYN_Y', 'dwellingType_Charter',
       'dwellingType_Family_joint', 'dwellingType_Half_Charter',
       'dwellingType_Monthly_rent', 'dwellingType_N',
       'dwellingType_Public_long_term_rental', 'dwellingType_Self',
       'housingType_Apartment', 'housingType_Detached_house',
       'housingType_Officetel', 'housingType_Related_multifamily_villa',
       'residenceClass_Average', 'residenceClass_Best', 'residenceClass_Good',
       'residenceClass_N', 'carOwnedYN_N', 'carOwnedYN_Y', 'loanType_Autoron',
       'loanType_LoanFinancingType', 'interestType_Fixed',
       'interestType_Mixed', 'interestType_Variable'
           ]


keys={
    'gender', 'age', 'education', 'maritalStatus', 'familyCount',
       'childCount', 'incomeType', 'incomeClass', 'occupation', 'orgType',
       'employedYears', 'houseOwnedYN', 'dwellingType', 'housingType',
       'residenceClass', 'carOwnedYN', 'loanType', 'carPrice', 'deposit',
       'loanTerm', 'interestType'
}

test_data={
	"applicationId": 1,
  "name": "12",
  "cellPhone": "1",
  "email": "123@132",
  "carPrice": 123213231.0,
  "loanType": "LoanFinancingType",
  "deposit": 10,
  "loanTerm": 36,
  "interestType": "Mixed",
  "maturity": [2027, 1, 12, 8, 33, 57],
  "appliedAt": [2024, 1, 12, 8, 33, 57],
  "createdAt": [2024, 1, 12, 8, 33, 57],
  "updatedAt": [2024, 1, 12, 8, 33, 57],
  "customerId": 1,
  "gender": "Woman",
  "education": "GraduateSchool",
  "maritalStatus": "Single",
  "incomeType": "Service",
  "incomeClass": "E",
  "occupation": "General_work",
  "orgType": "Trade",
  "houseOwnedYN": "Y",
  "dwellingType": "Self",
  "housingType": "Apartment",
  "residenceClass": "Good",
  "carOwnedYN": "N",
  "childCount": 0,
  "age": 21.0,
  "employedYears": 2.3,
  "familyCount": 2,
  "houseAge": 0.0
}
# print(data)
